{% set name = "brukerapi" %}
{% set version = "0.4.6" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/brukerapi-{{ version }}.tar.gz
  sha256: 24616ea608169cdc7b67f935da403cfd5475824d8637b7f8625350c25887fd52

build:
  number: 0
  noarch: python
  entry_points:
    - bruker=brukerapi.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >={{ python_min }}
    - setuptools >=64
    - wheel
  run:
    - python >={{ python_min }}
    - numpy >=1.26.0
    - pyyaml

test:
  imports:
    - brukerapi
  commands:
    - pip check
    - bruker --help
  requires:
    - python >={{ python_min }}
    - pip

about:
  home: https://github.com/isi-nmr/brukerapi-python
  summary: Python package providing I/O interface for MR datasets in the Bruker proprietary data format
  license: MIT
  license_file: LICENSE
  doc_url: https://bruker-api.readthedocs.io/

extra:
  recipe-maintainers:
    - wtclarke
    - headmeister
    - tomas-psorn
